name: lambda
version: 0.0.1
description: A bunch of Dart code
authors:
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/yjbanov/lambda
sdk: ">=1.10.0"
dependencies:
  uix:
    git: https://github.com/localvoid/uix
  analyzer: ">=0.25.0 <0.26.0"
  args: any
  barback: ">=0.15.2 <0.16.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  test: any
  guinness: any
  path: any
  html: any
transformers:
- lambda:
    $include: web/tests/*
- $dart2js:
    $exclude: web
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
