name: lambda
version: 0.0.1
description: A bunch of Dart code
authors:
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/yjbanov/lambda
sdk: ">=1.10.0"
dependencies:
  analyzer: ">=0.26.1 <1.0.0"
  args: ">=0.13.2 <1.0.0"
  barback: ">=0.15.2 <1.0.0"
  browser: ">=0.10.0+2 <1.0.0"
  dart_style: ">=0.2.0"
dev_dependencies:
  test: ">=0.12.4 <1.0.0"
  path: ">=1.0.0 <2.0.0"
  petitparser: ">=1.4.3 <2.0.0"
transformers:
- lambda:
    $include:
      - web/tests/*
      - test
- $dart2js:
    $exclude:
      - web
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
